eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:11100/eureka/
management:
    server:
        add-application-context-header: false
server:
    port: 11200
spring:
    application:
        name: wdhw-eureka-zuul-service
    servlet:
        multipart:
            max-file-size: 400MB
            max-request-size: 400MB
zuul:
    ignoredPatterns: /account/innerWallet/**,/huitongche/hunter/getActivityBonus/**,/huitongche/hunter/checkActivityBonus/**,/huitongche/hunter/test/**
    routes:
        lms:
            path: /lms/**
            serviceId: wd-lms-service
            #开启cookie
            sensitiveHeaders:
        api:
            path: /api/**
            serviceId: wdhw-api-server
        web:
            path: /web/**
            serviceId: wdhw-web-server