management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 18085
spring:
    application:
        name: wdhw-gateway-server
    cloud:
        gateway:
            routes:
            -   filters:
                - StripPrefix=1
                id: nacos-route
                predicates:
                -   args[pattern]: /nacos/**
                    name: Path
                uri: lb://wdhw-api-server
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
