server:
    port: 11900
spring:
    application:
        name: wdhw-gateway-server
    cloud:
        gateway:
          routes:
            - predicates:
                - Path=/api/**
#                 uri: http://192.168.5.22:8080
              uri: lb://wdhw-api-server
              filters:
                 - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: '*'

