server:
  port: 11300
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: wdhw-api-server
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
#      datasource:
#        ds1:
#          file:
#            file: 'classpath: flowrule.json'
#            data-type: json
#            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
logging:
  level:
    root: info



ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
feign:
  hystrix:
    enabled: true