server:
  port: 11301
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: wdhw-web-server
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: WDHW-EUREKA-CONFIG-SERVER
      name: wdhw-web-server
      profile: dev
  rabbitmq:
    addresses: 192.168.5.22
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:11100/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    leaseRenewalIntervalInSeconds: 30
    preferIpAddress: true
#新版配置，否则后面dashboard无法找到hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
feign:
  hystrix:
    enabled: true
logging:
  level:
    root: info