server:
  port: 11301
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: wdhw-web-server

management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
fegin:
  hystrix:
    enabled: true
logging:
  level:
    root: info