server:
    port: 11500
spring:
    application:
        name: wdhw-admin-server
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: refresh,health,info,env,loggers,metrics,trace,dump
