server:
    port: 9411
spring:
    application:
        name: wdhw-zipkin-server
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: refresh,health,info,env,loggers,metrics,trace,dump
    metrics:
        web:
            server:
                auto-time-requests: false

